export enum FileType {
  AAC = "audio/aac",
  AI = "application/postscript",
  AVI = "video/x-msvideo",
  BMP = "image/bmp",
  CSS = "text/css",
  CSV = "text/csv",
  DOC = "application/msword",
  DOCX = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  EOT = "application/vnd.ms-fontobject",
  EPS = "application/postscript",
  FLV = "video/x-flv",
  GIF = "image/gif",
  HTML = "text/html",
  ICO = "image/x-icon",
  INDD = "application/x-indesign",
  JPEG = "image/jpg", 
  JPG = "image/jpeg",
  JS = "application/javascript",
  JSON = "application/json",
  M4A = "audio/x-m4a",
  MKV = "video/x-matroska",
  MOV = "video/quicktime",
  MP3 = "audio/mpeg",
  MP4 = "video/mp4",
  OTF = "font/otf",
  PDF = "application/pdf",  
  PNG = "image/png",
  PPT = "application/vnd.ms-powerpoint",
  PPTX = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  PSD = "image/vnd.adobe.photoshop",
  RAR = "application/x-rar-compressed",
  SVG = "image/svg+xml",
  TTF = "font/ttf",
  TXT = "text/plain",
  WEBP = "image/webp",
  WOFF = "font/woff",
  WOFF2 = "font/woff2",
  XLS = "application/vnd.ms-excel",
  XLSX = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  XML = "application/xml",
  ZIP = "application/zip",
}

export const fileTypeGroup = {
  image: [
    FileType.JPEG,
    FileType.JPG,
    FileType.PNG,
  ]
}