import type { AuctionArtist, AuctionItem, AuctionSeries } from "./types";

const T = (offsetMs: number) =>
  new Date(new Date("2026-05-22T12:00:00Z").getTime() + offsetMs).toISOString();
const H = (h: number) => T(h * 3_600_000);
const D = (d: number) => T(d * 86_400_000);

const BASE = "https://hxextekspksdfloqajep.supabase.co/storage/v1/object/public/adoptable/68eac101-5595-4df2-8621-195d2b180467";
const IMG = (file: string) => `${BASE}/${file}`;

const PAYPAL = {
  name: "PayPal",
  iconUrl: "https://hxextekspksdfloqajep.supabase.co/storage/v1/object/public/app/icon/payment%20method/paypal.svg",
  accountValue: "parareem_preme",
};
const BMAC = {
  name: "Buy Me a Coffee",
  iconUrl: "https://hxextekspksdfloqajep.supabase.co/storage/v1/object/public/app/icon/payment%20method/buy-me-a-coffee.svg",
  accountValue: "parareem_preme",
};

const PREME: AuctionArtist = {
  username: "parareem_preme",
  displayName: "Preme ☆彡",
  profilePictureUrl:
    "https://cdn.discordapp.com/avatars/272227350895394816/6f8335e9940c524a316357f2d73d119f.png",
  paymentMethods: [PAYPAL, BMAC],
};

export const MOCK_AUCTION_SERIES: AuctionSeries[] = [
  /* ──────────────────────────────────────────────────────── */
  /*  special auctions 🔞  — premium NSFW, paired versions  */
  /* ──────────────────────────────────────────────────────── */
  {
    name: "special auctions 🔞",
    color: "#C77DFF",
    items: [
      {
        id: "900f9c33-7e70-427a-a3e2-5e22deb3e65b",
        number: 37,
        imageUrl: IMG("37.jpg"),
        status: "open",
        isNSFW: true,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: 280,
        currentBid: 120,
        bidCount: 3,
        endTime: D(3),
        artist: PREME,
        tags: [{ name: "Mermaid", color: "#B8A0E0" }],
        series: "special auctions 🔞",
      },
      {
        id: "cfdcb4a6-e44a-4074-9430-481c3b1a7f64",
        number: 36,
        imageUrl: IMG("36.jpg"),
        status: "open",
        isNSFW: true,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: 280,
        currentBid: null,
        bidCount: 0,
        endTime: D(5),
        artist: PREME,
        tags: [{ name: "Kitsune", color: "#40F0E8" }],
        series: "special auctions 🔞",
      },
      {
        id: "e3444c58-c7dc-4b7b-9b80-c4da77cedb65",
        number: 23,
        imageUrl: IMG("2300.png"),
        status: "closed",
        isNSFW: true,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: 200,
        currentBid: 110,
        bidCount: 4,
        endTime: D(-3),
        artist: PREME,
        tags: [{ name: "Mummy", color: "#FFB3D9" }],
        series: "special auctions 🔞",
      },
      {
        id: "bf59bd3a-9259-44f7-aa18-bf54a18efa41",
        number: 22,
        imageUrl: IMG("2200.png"),
        status: "closed",
        isNSFW: true,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: 200,
        currentBid: 160,
        bidCount: 9,
        endTime: D(-7),
        artist: PREME,
        tags: [{ name: "Kitsune", color: "#40F0E8" }],
        series: "special auctions 🔞",
      },
    ],
  },

  /* ──────────────────────────────────────────────────────── */
  /*  special auctions ⭐  — premium SFW, paired versions   */
  /* ──────────────────────────────────────────────────────── */
  {
    name: "special auctions ⭐",
    color: "#FFB300",
    items: [
      {
        id: "de6d7c95-e2c5-4969-aa36-f4a8448c2a2a",
        number: 30,
        imageUrl: IMG("30.jpg"),
        status: "open",
        isNSFW: false,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: 300,
        currentBid: 130,
        bidCount: 4,
        endTime: D(2),
        artist: PREME,
        tags: [{ name: "Kitsune", color: "#40F0E8" }],
        series: "special auctions ⭐",
      },
      {
        id: "db3e43cf-a586-42c2-914b-3f174dba099f",
        number: 29,
        imageUrl: IMG("29.png"),
        status: "open",
        isNSFW: false,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: 200,
        currentBid: 80,
        bidCount: 1,
        endTime: D(6),
        artist: PREME,
        tags: [{ name: "Vampire", color: "#E0A0C0" }],
        series: "special auctions ⭐",
      },
      {
        id: "7aa54e71-4bbe-491c-841e-dc0b6b332425",
        number: 24,
        imageUrl: IMG("24.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: 200,
        currentBid: 140,
        bidCount: 7,
        endTime: D(-5),
        artist: PREME,
        tags: [{ name: "Mermaid", color: "#B8A0E0" }],
        series: "special auctions ⭐",
      },
      {
        id: "aa690bf7-9009-41a6-bfb2-e0898080d7c8",
        number: 15,
        imageUrl: IMG("15.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 70,
        minIncrement: 5,
        autoBuy: 180,
        currentBid: 100,
        bidCount: 7,
        endTime: D(-14),
        artist: PREME,
        tags: [{ name: "Demon", color: "#C77DFF" }],
        series: "special auctions ⭐",
      },
    ],
  },

  /* ──────────────────────────────────────────────────────── */
  /*  boyfu auctions 🙂  — male characters                  */
  /* ──────────────────────────────────────────────────────── */
  {
    name: "boyfu auctions 🙂",
    color: "#42A5F5",
    items: [
      {
        id: "e97a28a2-5463-4dab-b40e-d184012003c8",
        number: 9,
        imageUrl: IMG("9.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 70,
        minIncrement: 5,
        autoBuy: 180,
        currentBid: 90,
        bidCount: 5,
        endTime: D(-21),
        artist: PREME,
        tags: [{ name: "Elf", color: "#B3FFB3" }],
        series: "boyfu auctions 🙂",
      },
      {
        id: "d357e3dc-6193-435a-b169-16f2c3355b82",
        number: 8,
        imageUrl: IMG("8.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 70,
        minIncrement: 5,
        autoBuy: null,
        currentBid: 85,
        bidCount: 3,
        endTime: D(-25),
        artist: PREME,
        tags: [{ name: "Sheep", color: "#FFBA47" }],
        series: "boyfu auctions 🙂",
      },
      {
        id: "925015f4-58eb-4719-9f41-1d193d87b82e",
        number: 7,
        imageUrl: IMG("7.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 60,
        minIncrement: 5,
        autoBuy: 150,
        currentBid: 75,
        bidCount: 4,
        endTime: D(-28),
        artist: PREME,
        tags: [{ name: "Android", color: "#A0F0E8" }],
        series: "boyfu auctions 🙂",
      },
      {
        id: "64d7aaa7-3b31-48f3-bd2a-ca9fc5a08000",
        number: 6,
        imageUrl: IMG("6.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 60,
        minIncrement: 5,
        autoBuy: 150,
        currentBid: 60,
        bidCount: 1,
        endTime: D(-30),
        artist: PREME,
        tags: [{ name: "Oni", color: "#FFB3D9" }],
        series: "boyfu auctions 🙂",
      },
    ],
  },

  /* ──────────────────────────────────────────────────────── */
  /*  sfw auctions ✅  — standard SFW                       */
  /* ──────────────────────────────────────────────────────── */
  {
    name: "sfw auctions ✅",
    color: "#66BB6A",
    items: [
      {
        id: "c05b9625-65a0-4627-89d0-e7aa8883c1e7",
        number: 31,
        imageUrl: IMG("31.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: 250,
        currentBid: 150,
        bidCount: 6,
        endTime: D(-2),
        artist: PREME,
        tags: [{ name: "Human", color: "#FFB3B3" }],
        series: "sfw auctions ✅",
      },
      {
        id: "86a9e850-cc51-44f5-923c-5b65916033fa",
        number: 28,
        imageUrl: IMG("28.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: null,
        currentBid: 80,
        bidCount: 1,
        endTime: D(-8),
        artist: PREME,
        tags: [{ name: "Dragon", color: "#FFA07A" }],
        series: "sfw auctions ✅",
      },
      {
        id: "cd6fda74-ab0d-4aff-8e01-a483f5c6285c",
        number: 22,
        imageUrl: IMG("22.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 70,
        minIncrement: 5,
        autoBuy: 180,
        currentBid: 90,
        bidCount: 5,
        endTime: D(-9),
        artist: PREME,
        tags: [{ name: "Human", color: "#FFB3B3" }],
        series: "sfw auctions ✅",
      },
      {
        id: "397b8fce-5f97-4ff2-a4d3-931194af6e83",
        number: 13,
        imageUrl: IMG("13.png"),
        status: "closed",
        isNSFW: false,
        startingBid: 70,
        minIncrement: 5,
        autoBuy: 180,
        currentBid: 105,
        bidCount: 8,
        endTime: D(-17),
        artist: PREME,
        tags: [{ name: "Mermaid", color: "#B8A0E0" }],
        series: "sfw auctions ✅",
      },
    ],
  },

  /* ──────────────────────────────────────────────────────── */
  /*  nsfw auctions 🔞  — standard NSFW                     */
  /* ──────────────────────────────────────────────────────── */
  {
    name: "nsfw auctions 🔞",
    color: "#EF5350",
    items: [
      {
        id: "1c0d3806-1b90-4cc1-ad61-f4b27fa3cbc5",
        number: 34,
        imageUrl: IMG("34.jpg"),
        status: "open",
        isNSFW: true,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: null,
        currentBid: 110,
        bidCount: 2,
        endTime: H(36),
        artist: PREME,
        tags: [{ name: "Kraken", color: "#80E0DB" }],
        series: "nsfw auctions 🔞",
      },
      {
        id: "a908e7cd-ed3e-4e82-a341-e797c4563920",
        number: 35,
        imageUrl: IMG("35.png"),
        status: "closed",
        isNSFW: true,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: 200,
        currentBid: 120,
        bidCount: 5,
        endTime: D(-1),
        artist: PREME,
        tags: [{ name: "Human", color: "#FFB3B3" }],
        series: "nsfw auctions 🔞",
      },
      {
        id: "709cdf6d-f3ef-46a6-ba2c-c1f6c9b7bf09",
        number: 33,
        imageUrl: IMG("33.png"),
        status: "closed",
        isNSFW: true,
        startingBid: 100,
        minIncrement: 10,
        autoBuy: 250,
        currentBid: 200,
        bidCount: 11,
        endTime: D(-4),
        artist: PREME,
        tags: [{ name: "Lamia", color: "#A0F0E8" }],
        series: "nsfw auctions 🔞",
      },
      {
        id: "7fd41da2-bca5-4b19-b6e4-a040acb56388",
        number: 27,
        imageUrl: IMG("27.png"),
        status: "closed",
        isNSFW: true,
        startingBid: 80,
        minIncrement: 10,
        autoBuy: null,
        currentBid: 90,
        bidCount: 2,
        endTime: D(-10),
        artist: PREME,
        tags: [{ name: "Kraken", color: "#80E0DB" }],
        series: "nsfw auctions 🔞",
      },
    ],
  },
];

export const MOCK_AUCTION_ALL: AuctionItem[] = MOCK_AUCTION_SERIES.flatMap((s) => s.items);

export const findMockAuction = (id: string): AuctionItem | undefined =>
  MOCK_AUCTION_ALL.find((item) => item.id === id);
